class EnergySummary:
    def __init__(self, total_watt_hours: float, total_cost: float, anomaly_count: int): ...
    @property
    def total_watt_hours(self) -> float: ...
    @property
    def total_cost(self) -> float: ...
    @property
    def anomaly_count(self) -> int: ...