class EnergyReading:
        def __init__(self, device_id: str, watt_hours: float): ...
        @property
        def device_id(self) -> str: ...
        @property
        def watt_hours(self) -> float: ...